### PR TITLE
Added IAV

### PR DESCRIPTION
**Pull request by InArgentumVeritas**
// Added IAV Swap
// Thanks in advance

### CODE REVIEW

**Comment by HebeBlock** [comment]
Hi, I can't access https://inagentumveritas.app, can you check it?

**Comment by InArgentumVeritas** [comment]
Oh yeah, i mistyped. it's inaRgentumveritas.. let me fix it real quick

**Comment by InArgentumVeritas** [comment]
Should be fine now.

**Comment by InArgentumVeritas** [comment]
let me know if there's any issues

**Comment by InArgentumVeritas** [comment]
Yeah, i mistyped. sorry :) ate the R in the word Argentum, hope its fine 
now

***@***.***

**Pull request merged**
